export const ACTIONS = Object.freeze({
  EXIT: "exit",
  OPEN_MY_STATION: "open_my_station",
  OPEN_STATUS: "open_status",
  OPEN_BOT_MESSAGES: "open_bot_messages",
  OPEN_STATIONS_TEAMS: "open_stations_teams",
  OPEN_RESET: "open_reset",
  BACK_TO_ADMIN_MENU: "back_to_admin_menu",
  BACK_TO_WHO_ARE_YOU: "back_to_who_are_you",
  PARTICIPANT_TEAM_SELECT: "participant_team_select",
  STATION_TEAM_SELECT: "station_team_select",
  STATION_FINISH: "station_finish",
  STATION_FORCE_FINISH: "station_force_finish",
  MESSAGE_CREATE: "message_create",
  MESSAGE_OPEN: "message_open",
  MESSAGE_TRIGGER_STATIONS: "message_trigger_stations",
  MESSAGE_TRIGGER_SELECT: "message_trigger_select",
  MESSAGE_TRIGGER_PAGE: "message_trigger_page",
  MESSAGE_RECORD_CONFIRM: "message_record_confirm",
  MESSAGE_RECORD_CANCEL: "message_record_cancel",
  MESSAGE_REPLACE: "message_replace",
  MESSAGE_DELETE: "message_delete",
  MESSAGES_MENU_BACK: "messages_menu_back",
  RESET_CONFIRM: "reset_confirm",
});
